<?php

namespace AppBundle\Repository\Entity;

/**
 * StocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StocksRepository extends \Doctrine\ORM\EntityRepository
{
}
